### ISSUE TITLE
AES Error? or so?

### ISSUE THREAD

**Issue by notna1109** [izneo-get/cafeyn-get#1]
After 6 times without any problems, here is what happened. I have changed the "cafeyn_authtoken" to be sure but still an issue

 File "cafeyn_get.py", line 278, in <module>
    aes = AES.new(key.encode('utf-8'), AES.MODE_CBC, key[0:16].encode('utf-8'))
  File "C:\Programs\Python\Python38\lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "C:\Programs\Python\Python38\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "C:\Programs\Python\Python38\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "C:\Programs\Python\Python38\lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (33 bytes)

**Comment by izneo-get** [comment]
Could you provide the link to the magazine you are trying to grab?

**Comment by notna1109** [comment]
https://reader.cafeyn.co/fr/596062/2010234

this is an example, but many of them are leading to the same error. I am french if you prefer sepak in french.

**Comment by izneo-get** [comment]
Quand je debug avec cette URL, en décodant une partie de la clé, je reçois à la place d'une suite de chiffres, un texte particulièrement déplacé : 

![Imgur](https://i.imgur.com/BhzIlYu.png)

Ils ont un drôle de sens de l'humour chez Cafeyn...

**Comment by izneo-get** [comment]
J'ai l'impression que cela arrive sur les titres "anciens". Est-ce que vous confirmez ou avez vous aussi rencontré le problème sur des titre plus récents ?

**Comment by notna1109** [comment]
Oui c'est beaucoup de titres anciens, mais je crois avoir testé sur des récents avec le même résultat. Je vais regarder tout de suite.

**Comment by notna1109** [comment]
> 
> 
> Quand je debug avec cette URL, en décodant une partie de la clé, je reçois à la place d'une suite de chiffres, un texte particulièrement déplacé :
> 
> ![Imgur](https://camo.githubusercontent.com/1bfe6dc02771ea55872fd1d305a2824a7142fc04/68747470733a2f2f692e696d6775722e636f6d2f42687a496c59752e706e67)
> 
> Ils ont un drôle de sens de l'humour chez Cafeyn...

C'est un peu limite quand même

**Comment by izneo-get** [comment]
> Oui je confirme que c'est avec les titres plus anciens mais ce qui est bizarre c'est qu'ils restent consultable avec le reader.

Je pense que la façon dont la clé de chiffrement est générée / la façon dont les PDF sont chiffrés était différente avant. 
Il faut que je me repenche dans leur script JS...

**Comment by notna1109** [comment]
> 
> 
> > Oui je confirme que c'est avec les titres plus anciens mais ce qui est bizarre c'est qu'ils restent consultable avec le reader.
> 
> Je pense que la façon dont la clé de chiffrement est générée / la façon dont les PDF sont chiffrés était différente avant.
> Il faut que je me repenche dans leur script JS...

Ok se serait super que tu y arrives :-)

**Comment by izneo-get** [comment]
Et voilà : 9a35ede !

J'ai quand même un peu en travers de la gorge le texte qu'ils utilisent dans leurs clés de chiffrement...

**Comment by notna1109** [comment]
Je suis assez d'accord avec toi. C'est inadmissible. Mais que peut-on y faire...
