### ISSUE TITLE
blocked my account

### ISSUE THREAD

**Issue by ibragab** [izneo-get/cafeyn-get#3]
It works well
Until yesterday
He blocked my account
With every new account, he holds a block

https://i.imgur.com/FUzNxIQ.png

**Comment by izneo-get** [comment]
Hello, 

I use `cafeyn_get.exe` on a weekly basis and I don't have any problem. 

Could you give more informations? 
Did you grabbed a fair amount of magazines? 
Did you contact support to unblock your account? 

When I tried to create an account last year (before using this script), I had the same message.

**Comment by ibragab** [comment]
Hi
I also use

>  cafeyn_get.exe

I don't use a VPN
Work from inside sever Windows 2019
Yes, I download almost all the daily magazines.
I tried to contact support, but I couldn't find a way.
I created a new account from another computer and it was working fine until the script started and started downloading. Only 5 pages of the magazine and my account was closed

**Comment by zarzor** [comment]
Also me
3 accounts banned
Just start download first 3 pages account banned automatically
Any help please
Thanks advance

**Comment by izneo-get** [comment]
Pour être bien sûr de comprendre : 
- Vous créez un nouveau compte. 
- Vous payez l'abonnement. 
- Vous lancez un téléchargement avec le script.
- Au bout de 3 pages, votre compte est bloqué. 

C'est bien ça ?

Je viens de tester en créant un nouveau compte, mais sans payer l'abonnement. 
J'ai lancé 10 téléchargements à la suite (journaux, magazines). 
A chaque fois, j'ai été limité aux 8 premières pages (normal, c'est la limitation du compte gratuit), mais le compte n'a pas été banni. 

Je ne sais pas ce qui provoque le blocage. 
Dans le doute, je rajoute une option : `--pause SECONDS` qui permet de faire une pause entre chaque page. 
6e17cdc89d8bc75dc1d11da73f246763d8a43574

**Comment by ibragab** [comment]
Is there a way to communicate with you on private?

**Comment by izneo-get** [comment]
Yes, give me an email where I can send you my private email.

**Comment by ibragab** [comment]
telegram

@ibragab

**Comment by alexlazk** [comment]
Salut! J'aime beaucoup vos scripts. Est-il possible de faire un script similaire pour Perlego ?  Le français n'est pas ma langue maternelle mais je le comprends sans problème.  Voici un émail anonyme pour mieux nous contacter eustaquiocorsair@protonmail.com

**Comment by izneo-get** [comment]
@alexlazk Je viens de regarder Perlego. Il semblerait que leur contenu est directement téléchargeable au format ePub ou PDF depuis la fiche produit. 
Je ne vois donc pas l'intérêt de faire un script qui fait l'équivalent d'un "clic-droit --> enregistrer sous...".

**Comment by alexlazk** [comment]
Merci de votre réponse. Non, je suppose que vous supposez cela parce que sous chaque livre se trouve son format (.ePUB/.PDF), mais il s'agit juste d'une référence, cela vous permet seulement de le visualiser en ligne. Lorsque vous utilisez l'application mobile, vous pouvez télécharger uniquement les documents au format 

PDF et les lire uniquement dans l'application.
Ils offrent un essai gratuit, mais je peux partager mon compte avec vous au cas où vous seriez intéressé par le script.

**Comment by izneo-get** [comment]
OK, je comprends mieux. 

Malheureusement, je ne souhaite pas me lancer dans le développement d'un script basé sur un service auquel je n'ai pas accès. Cela signifierait que je ne pourrais pas le mettre à jour.
