### ISSUE TITLE
NameError: name 'save_path' is not defined

### ISSUE THREAD

**Issue by notna1109** [izneo-get/cafeyn-get#4]
Hello,  sans raisons particulière j'ai cela qui apparait alors que tout fonctionnait bien il y a trois jours. Je n'ai pas changé le 'path' j'ai laissé par défaut. Enfin rien n'a changé depuis la dernière fois où je m'en suis servi et qu'il a très bien fonctionné:

E:\Programmes\Python\cafeyn-get-0.06.2>python cafeyn_get.py https://reader.cafeyn.co/fr/2010920/21680295
Impossible de récupérer la page 2

Compilation du PDF...
Traceback (most recent call last):
  File "cafeyn_get.py", line 345, in <module>
    for fname in os.listdir(save_path):
NameError: name 'save_path' is not defined

Pour info j'utilise via un cmd sous windows. Je n'ai jamais eu de problèmes. J'ai mis la dernière version mais cela n'a rien changé. Merci

**Comment by izneo-get** [comment]
Effectivement, il y a un changement chez Cafeyn qui fait qu'on ne doit plus appeler les pages de la même manière. 

Je viens de faire une mise à jour : 8820026

Dites moi si c'est OK pour vous.

**Comment by notna1109** [comment]
Oui cela fonctionne parfaitement. Merci encore !

**Comment by Olaf1607** [comment]
Bonjour,

J'ai également cette erreur depuis ce matin.
