### ISSUE TITLE
Télécharger à partir d'un fichier

### ISSUE THREAD

**Issue by B0pol** [izneo-get/cafeyn-get#5]
Bonjour,
ce serait très pratique de pouvoir utiliser cafeyn-get à partir d'un fichier, le format le plus simple serait un fichier texte avec un URL par ligne.

**Comment by izneo-get** [comment]
Je note pour une prochaine version.

**Comment by izneo-get** [comment]
C'est disponible dans f91d2508f8e8b03d36f281db269d90f267e7a4bf
