### ISSUE TITLE
Pages dans le désordre

### ISSUE THREAD

**Issue by Th0mC** [izneo-get/cafeyn-get#7]
Bonjour,
Je viens de tester sur un numéro d'une revue et le pdf est bien téléchargé mais toutes les pages sont dans le désordre.
Tom

**Comment by SwissAdi** [comment]
Bonjour Je fais suite au problème soulevé et effectivement j'ai le même souci... je viens de tester sur cette url : https://reader.cafeyn.co/fr/1979943/21728950

**Comment by izneo-get** [comment]
Sous quel OS êtes vous ? 

Je pense que la fonction `os.listdir(save_path)` retourne les fichiers triés par nom sous Windows, mais pas sous Linux. 

Je n'arrive toujours pas à me connecter à Cafeyn, je ne peux donc pas débugger. 

Pouvez-vous essayer en remplaçant la ligne 
```
        for fname in os.listdir(save_path):
```
par
```
        for fname in sorted(os.listdir(save_path)):
```
?

**Comment by SwissAdi** [comment]
oui ça fonctionne avec sorted :) sous Debian ? (Ubuntu server)

**Comment by izneo-get** [comment]
Corrigé dans 619ba7e
