### ISSUE TITLE
File "cafeyn_get.py", line 285 - File "/usr/lib/python3.8/json/__init__.py", line 357 -  File "/usr/lib/python3.8/json/decoder.py", line 355,

### ISSUE THREAD

**Issue by SwissAdi** [izneo-get/cafeyn-get#8]
Coucou,

Je suis assez nouveau donc excusez par avance si la question posé semble naïve.

J'ai réussi à générer un PDF pour un magazine (cité dans une des deux issues "raised") mais bizarrement pour Le Figaro j'ai ce message sans vraiment comprendre ce qui pourrai en être à l'origine.

J'utilise une distribution Ubuntu server clean et j'utilise python3 plutôt que python.
Je ne sais pas si cela a une incidence ?

Salutattions
Adi

[INFO] URL: https://reader.cafeyn.co/fr/1979943/21728950
Traceback (most recent call last):
  File "cafeyn_get.py", line 285, in <module>
    mag_infos = json.loads(r.text)["result"]
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by izneo-get** [comment]
Le script est fait pour tourner avec Python 3.

L'erreur que vous remontez signifie "je n'ai pas réussi à charger les informations liées à cette publication". 

En ce moment, Cafeyn a une politique de blocage hyper stricte. Au moindre soupçon (utilisation d'un VPN, utilisation d'une IP partagée, lecture de plusieurs pages en un temps restreint, lecture de plusieurs magazines dans un temps restreint, ...), le compte est bloqué et il n'est plus possible de récupérer un magazine. 

Pour le moment, il est plus sûr d'utiliser la version "Selenium" qui simule la navigation par navigateur (mais qui ne retourne pas un "vrai" PDF).

**Comment by SwissAdi** [comment]
Bonjour,

Merci pour le retour, mon compte ne semble pas bloqué. Du coups je me dis que peut être c'est lié au fait que j'ai peut être fait quelque chose de travers avec les cookies ? pour les cookies sur ose j'ai dû utilisé sqlite pour les lires et je pense y être parvenu mais peut être que le champs affiché omet un certain nombre de caractère ?

pour example le "Cafeyn_authtoken_V2" (que je suppose correspond au "Cafeyn_authtoken" du fichier de config ?) a 56 caractères et pour le cookiesConsent aussi. Me manquerai t'il des caractères ?

Merci en tout cas pour l'aide et ce script qui a l'air pas mal :)

Salutations

**Comment by izneo-get** [comment]
Je vous conseille d'utiliser la console de développement de Firefox ou Chrome pour regarder le contenu des cookies. 

## Chrome
Menu --> Plus d'outils --> Outils de développements
Application / Storage / Cookies
et recherchez le cookie "https://reader.cafeyn.co".

## Firefox
Menu --> Developpement web --> Inspecteur de stockage --> Cookies
et recherchez le cookie "https://reader.cafeyn.co".

**Comment by SwissAdi** [comment]
Magnifique c'était effectivement ça le souci... en utilisant sqllite pour lire les cookies ce qui était affiché sur le terminal n'était qu'une fraction de la chaine total de caractères.

Merci Izneo-get c'était effectivement plus facile au travers de Firefox

Salutations 👍
